#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

sudo apt-get install -y emacs24-nox curl tree unzip zip mosh zsh

cd $(dirname $0)

# Copy over resources
cp .zshrc ~
cp .gitconfig ~
cp .tmux.conf ~

# Copy over my .emacs.d
sudo -iu syme git clone -b basic git://github.com/abizern/prelude.git ~/.emacs.d

# Enable vim
cp .vimrc ~
sudo -iu syme git clone --recursive git://github.com/Abizern/vimdotfiles.git ~/.vim

# Once that's done, run emacs in daemon mode.
emacs --daemon
