#!/bin/bash

set -e

# Not really using these yet:
PROJECT=$1

sudo apt-get install -y emacs24-nox curl tree unzip zip mosh zsh

cd $(dirname $0)

# Copy over resources
cp .zshrc ~
cp .gitconfig ~
cp .tmux.conf ~
cp .vimrc ~
cp .gemrc ~

# Install hub
sudo chmod +x hub
sudo cp hub /usr/local/bin

# Copy over my .emacs.d
git clone -b basic git://github.com/Abizern/prelude.git ~/.emacs.d

# Copy over my vim dotfiles dir
git clone --recursive git://github.com/Abizern/vimdotfiles.git ~/.vim
